### ISSUE TITLE
strange error mensages

### ISSUE THREAD

**Issue by KimeruReru** [SoulMelody/LibreSVIP#338]
it always happens when i try to convert english files to cevio
specially svp's
this bugs are always when i try to convert svp files and i don't know why

Traceback (most recent call last):
  File "libresvip\gui\modules\task_manager.py", line 126, in run
  File "D:\Synthesizer V Studio Pro\LibreSVIP\_internal\libresvip\plugins\ccs\cevio_converter.py", line 30, in dump
    serializer = XmlSerializer(
                 ^^^^^^^^^^^^^^
  File "<string>", line 3, in __init__
  File "xsdata_pydantic\bindings.py", line 34, in __init__
  File "xsdata\formats\dataclass\context.py", line 51, in __init__
  File "xsdata\formats\dataclass\compat.py", line 141, in get_type
KeyError: 'pydantic'

**Comment by SoulMelody** [comment]
This error is due to the packaging script, please re-download version 1.1.8 from the release page

**Comment by SoulMelody** [comment]
Solved via https://github.com/SoulMelody/LibreSVIP/commit/d1a9a1f7d57747694aeaedfda35b976bb1012c87
